[workspace]
members = [
    "isolated-lending-protocol",
    "lending-protocol",
    "rewards-booster",
    "liquid-staking",
    "ush-facilitators",
    "account-manager",
    "ush-staking",
]
resolver = "2"
